### ISSUE TITLE
error in workflow - when trying to use the workflow

### ISSUE THREAD

**Issue by saqebakhter** [MuppetGate/Alfred-Workflows-DateCalculator#2]
Whenever i try to do a date calc  i.e) dcalc today - 6w i get this error : 

Error in workflow 'muppet.gate.net.DateCalculator' 
u 'ampersand'

Any idea ?

**Comment by MuppetGate** [comment]
Mmm. Not seeing this on mine. 

I tend to just use the repo here to store the files; it's probably not a good idea to build the workflow yourself from here (I've never tried it myself). Could you try downloading from here to see if it gives you the same result?

(http://www.packal.org/workflow/date-calculator)

**Comment by saqebakhter** [comment]
Yup. I got it from packal not from github.  Just reporting the issue here

**Comment by MuppetGate** [comment]
Most odd. Can you switch on debug from Alfred's preferences and post the full output for the workflow. 

I'm thinking that it could be an incompatibility with the version of Python it is finding. Are you using the one installed with OSX?

**Comment by MuppetGate** [comment]
Yeah, send the debug output

**Comment by MuppetGate** [comment]
Ah, something has occurred to me. I'll take a look.

**Comment by MuppetGate** [comment]
Dammit! Found the problem! I'll sort out a fix later. Thanks for reporting.

**Comment by MuppetGate** [comment]
Heh heh ... Good one.

**Comment by saqebakhter** [comment]
Cool thanks let me know when you update packal and I'll try it again!

**Comment by MuppetGate** [comment]
Hi. I've put an update on Packal. Could you give it a try?

**Comment by saqebakhter** [comment]
Nope still getting an error here is the debug log : 

Starting debug for 'Date Calculator'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:34:12 workflow.py:1830 ERROR    u'ampersand'
Traceback (most recent call last):
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/workflow/workflow.py", line 1828, in run
    func(self)
  File "date_calculator.py", line 300, in main
    command_parser = DateParser(wf.settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_parser.py", line 15, in __init__
    self.full_date_time_expression = get_full_format_regex(settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_functions.py", line 54, in get_full_format_regex
    return DATE_TIME_MAPPINGS[settings['date-time-format']]['date-time-format'](
KeyError: u'ampersand'
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:34:12 workflow.py:1830 ERROR    u'ampersand'
Traceback (most recent call last):
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/workflow/workflow.py", line 1828, in run
    func(self)
  File "date_calculator.py", line 300, in main
    command_parser = DateParser(wf.settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_parser.py", line 15, in __init__
    self.full_date_time_expression = get_full_format_regex(settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_functions.py", line 54, in get_full_format_regex
    return DATE_TIME_MAPPINGS[settings['date-time-format']]['date-time-format'](
KeyError: u'ampersand'
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:34:13 workflow.py:1830 ERROR    u'ampersand'
Traceback (most recent call last):
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/workflow/workflow.py", line 1828, in run
    func(self)
  File "date_calculator.py", line 300, in main
    command_parser = DateParser(wf.settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_parser.py", line 15, in __init__
    self.full_date_time_expression = get_full_format_regex(settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_functions.py", line 54, in get_full_format_regex
    return DATE_TIME_MAPPINGS[settings['date-time-format']]['date-time-format'](
KeyError: u'ampersand'
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:34:13 workflow.py:1830 ERROR    u'ampersand'
Traceback (most recent call last):
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/workflow/workflow.py", line 1828, in run
    func(self)
  File "date_calculator.py", line 300, in main
    command_parser = DateParser(wf.settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_parser.py", line 15, in __init__
    self.full_date_time_expression = get_full_format_regex(settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_functions.py", line 54, in get_full_format_regex
    return DATE_TIME_MAPPINGS[settings['date-time-format']]['date-time-format'](
KeyError: u'ampersand'
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:34:13 workflow.py:1830 ERROR    u'ampersand'
Traceback (most recent call last):
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/workflow/workflow.py", line 1828, in run
    func(self)
  File "date_calculator.py", line 300, in main
    command_parser = DateParser(wf.settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_parser.py", line 15, in __init__
    self.full_date_time_expression = get_full_format_regex(settings)
  File "/Users/saqakhte/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.99520EA9-3FAC-4E22-A132-5E5907042955/date_functions.py", line 54, in get_full_format_regex
    return DATE_TIME_MAPPINGS[settings['date-time-format']]['date-time-format'](
KeyError: u'ampersand'

-- 
Saqeb Akhter


On January 13, 2015 at 7:35:32 PM, MuppetGate (notifications@github.com) wrote:

Hi. I've put an update on Packal. Could you give it a try?

**Comment by MuppetGate** [comment]
Bugger. I thought that might happen. It appear that the incorrect key has been saved in your settings file.

You have two options:

**Option 1:** The easy one. delete your settings file and then the workflow will rebuild it using the correct one. To do this just execute the following command in Alfred:

**dcalc workflow:del settings**

The problem is that if you have saved any anniversaries then they will get wiped too.

**Option 2:** Alter the offending entry from the settings file. This is the trickier one, but will allow you to keep your anniversary list. To do this, execute the following command in Alfred:

**dcalc workflow:open data**

This will open the folder where the workflow's settings file is stored. You should find a file here called _settings.json_. Edit the file and replace the line

  **"date-time-format": "ampersand",**

with 

**"date-time-format": "@",**

Save the file.

I would recommend Option 1.

Anyway, try one of those and let me know what happens.

**Comment by saqebakhter** [comment]
Actually both options don’t work - since it rquires using the ‘dcalc’ - it ends up giving the same error so i can del the settings or open data.

Is there a way to delete the settings via terminal ? Or some other way that doesn’t need the dcalc workflow to run ? 

-- 
Saqeb Akhter


On January 14, 2015 at 12:51:01 AM, MuppetGate (notifications@github.com) wrote:

Bugger. I thought that might happen. It appear that the incorrect key has been saved in your settings file.

You have two options:

Option 1: The easy one. delete your settings file and then the workflow will rebuild it using the correct one. To do this just execute the following command in Alfred:

dcalc workflow:del settings

The problem is that if you have saved any anniversaries then they will get wiped too.

Option 2: Alter the offending entry from the settings file. This is the trickier one, but will allow you to keep your anniversary list. To do this, execute the following command in Alfred:

dcalc workflow:open data

This will open the folder where the workflow's settings file is stored. You should find a file here called settings.json. Edit the file and replace the line

"date-time-format": "ampersand",

with

"date-time-format": "@",

Save the file.

I would recommend Option 1.

Anyway, try one of those and let me know what happens.

**Comment by saqebakhter** [comment]
Scratch that i found the settings.json file - deleted it , and now everything is good!!

Thanks!

-- 
Saqeb Akhter


On January 14, 2015 at 1:56:45 AM, Saqeb Akhter (saqeb.akhter@gmail.com) wrote:

Actually both options don’t work - since it rquires using the ‘dcalc’ - it ends up giving the same error so i can del the settings or open data.

Is there a way to delete the settings via terminal ? Or some other way that doesn’t need the dcalc workflow to run ? 

-- 
Saqeb Akhter


On January 14, 2015 at 12:51:01 AM, MuppetGate (notifications@github.com) wrote:

Bugger. I thought that might happen. It appear that the incorrect key has been saved in your settings file.

You have two options:

Option 1: The easy one. delete your settings file and then the workflow will rebuild it using the correct one. To do this just execute the following command in Alfred:

dcalc workflow:del settings

The problem is that if you have saved any anniversaries then they will get wiped too.

Option 2: Alter the offending entry from the settings file. This is the trickier one, but will allow you to keep your anniversary list. To do this, execute the following command in Alfred:

dcalc workflow:open data

This will open the folder where the workflow's settings file is stored. You should find a file here called settings.json. Edit the file and replace the line

"date-time-format": "ampersand",

with

"date-time-format": "@",

Save the file.

I would recommend Option 1.

Anyway, try one of those and let me know what happens.

**Comment by MuppetGate** [comment]
Mm. Okay thanks for letting me know. I might have to adjust the code so that settings can always be deleted.
